{% set name = "openff-toolkit" %}
{% set version = "0.18.0" %}
{% set python_min = '3.11' %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  git_url: https://github.com/openforcefield/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1

build:
  number: 0

outputs:
  - name: openff-toolkit-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - versioningit
      run:
        - python >={{ python_min }},<3.14a0
        - packaging
        - numpy
        - openff-forcefields
        - openff-amber-ff-ports >=0.0.4
        - openff-units
        - openff-utilities
        - networkx >=2.5
        - xmltodict
        - bson
        - python-constraint
        - cachetools
        - typing_extensions
      run_constrained:
        - openforcefield ==9999999999
        - pydantic <3.0.0a0
        - qcportal >=0.50.0

    test:
      requires:
        - python {{ python_min }}
      imports:
        - openff.toolkit

  - name: openff-toolkit
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<3.14a0
        - openmm >=7.6
        - openff-interchange ~=0.4.0
        - rdkit !=2024.03.6
        - ambertools >=22
        - mdtraj
        - {{ pin_subpackage('openff-toolkit-base', exact=True) }} 
        - notebook
        - ipywidgets
        - openff-nagl >=0.4

    test:
      requires:
        - python {{ python_min }}
        - qcportal
      imports:
        - openff.toolkit
        - rdkit
      files:
        - test_openff_toolkit.py
      commands:
        - python test_openff_toolkit.py

  - name: openff-toolkit-examples
    script: move-examples.sh
    build:
      noarch: python

    requirements:
      run:
        - python >={{ python_min }},<3.13
        - nglview
        - jupyterlab
        - qcelemental
        - qcportal >=0.50.0
        - qcengine
        - openmmforcefields
        - pdbfixer
        - {{ pin_subpackage('openff-toolkit', exact=True) }}

    test:
      requires:
        - python {{ python_min }}
      files:
        - test_examples_copied.py
      source_files:
        - examples
      commands:
        - python test_examples_copied.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern, extensible library for molecular mechanics force field science from the Open Force Field Initiative
  description: |
    The Open Force Field Toolkit, built by the Open Force Field Initiative, is a Python
    toolkit for the development and application of modern molecular mechanics force fields
    based on direct chemical perception and rigorous statistical parameterization methods.
  doc_url: https://docs.openforcefield.org/projects/toolkit/en/stable/
  dev_url: https://github.com/openforcefield/openff-toolkit

extra:
  recipe-maintainers:
    - jaimergp
    - j-wags
    - mattwthompson
